"""Update user table with roles and firebase_uid

Revision ID: 5ceeeb281277
Revises: 3d0a407d4ed8
Create Date: 2026-05-10 15:38:06.151599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ceeeb281277'
down_revision = '3d0a407d4ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('user', 'admin'), nullable=False))
        batch_op.add_column(sa.Column('login_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('google_id'))
        batch_op.create_unique_constraint(None, ['firebase_uid'])
        batch_op.drop_column('google_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('google_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('google_id'), ['google_id'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('firebase_uid')
        batch_op.drop_column('login_provider')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
